#!/usr/bin/env python3
"""make-director-cards.py — emit the marketing director's share-card variants as SVG source.

Text is composed here, never generated by a model, so a party name or a number cannot be
hallucinated into an asset. Rasterise with:
    node marketing/tools/render-card.js <svg> <png> --w <W> --h <H>

Colours come from marketing/02-design-system/tokens.json (ink ramp + brand accent). The palette
is grey plus one accent on purpose: the product is method-neutral and the card must not signal a
lean. No party colour appears anywhere in these cards.

Type sizes are fitted, not guessed. The first version of this script used sizes that looked right
in a spec dict and silently overflowed the 1080px artboards, clipping the headline. Every run of
text now goes through fit(), which measures the real glyph width with the actual Inter file and
shrinks until it fits.

Prerequisite for rasterising: Inter must be resolvable by fontconfig, because sharp renders SVG
text through pango and matches font-family by name, not by file path.
    cp marketing/assets/fonts/Inter.ttf ~/.local/share/fonts/ && fc-cache -f
"""
import json
import os

from PIL import ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "marketing", "assets", "og")
FONT = os.path.join(ROOT, "marketing", "assets", "fonts", "Inter.ttf")

_font_cache = {}


def _font(size, weight):
    key = (size, weight)
    if key not in _font_cache:
        f = ImageFont.truetype(FONT, size)
        if weight >= 600:
            try:
                f.set_variation_by_name("SemiBold")
            except Exception:
                pass
        _font_cache[key] = f
    return _font_cache[key]


def fit(text, max_w, start, weight=400, floor=12, fill=0.94):
    """Largest size <= start whose rendered width fits within max_w * fill."""
    limit = max_w * fill
    for size in range(int(start), floor - 1, -1):
        try:
            if _font(size, weight).getlength(text) <= limit:
                return size
        except OSError:
            break
    return floor


# From tokens.json / globals.css.
INK_900 = "#14171c"   # canvas
INK_50 = "#f7f8fa"    # primary text on dark
INK_300 = "#b6bcc7"   # secondary text
INK_400 = "#8b93a1"   # tertiary text
ACCENT = "#1f4e79"    # the single accent
RULE = "#2b3038"      # hairline

H1 = "Answer 18 statements."
H2 = ["See where you line up with each party's", "published positions."]
FOOT = "Every position quoted and archived \u00b7 nothing about you leaves your browser"
WORDMARK = "BC Vote Match"

# Per-ratio *starting* sizes and space. The fitter reduces any of these that would overflow.
SPECS = {
    "og":       dict(w=1200, h=630,  m=72, mark=88,  wm=34, h1=70, h2=34, foot=22),
    "x":        dict(w=1600, h=900,  m=96, mark=112, wm=42, h1=88, h2=43, foot=28),
    "square":   dict(w=1080, h=1080, m=88, mark=136, wm=40, h1=88, h2=41, foot=25),
    "portrait": dict(w=1080, h=1350, m=88, mark=152, wm=41, h1=94, h2=43, foot=26),
}

MARK = (
    '<g transform="translate({x},{y}) scale({s})">'
    '<rect width="64" height="64" rx="12" fill="{accent}"/>'
    '<path d="M18 33 L29 44 L46 20" fill="none" stroke="{ink50}" stroke-width="4" '
    'stroke-linecap="round" stroke-linejoin="round"/>'
    '<circle cx="46" cy="11" r="5.5" fill="{ink50}"/>'
    "</g>"
)


def card(s):
    w, h, m = s["w"], s["h"], s["m"]
    inner = w - 2 * m
    mark_s = s["mark"] / 64.0

    # Every text run fitted to the artboard before it is placed.
    wm_sz = fit(WORDMARK, inner - s["mark"] * 1.5, s["wm"], weight=600)
    h1_sz = fit(H1, inner, s["h1"], weight=600, fill=0.97)
    h2_sz = [fit(t, inner, s["h2"]) for t in H2]
    foot_sz = fit(FOOT, inner, s["foot"])

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
        f'viewBox="0 0 {w} {h}" role="img" aria-label="BC Vote Match">',
        f'<rect width="{w}" height="{h}" fill="{INK_900}"/>',
    ]
    # Left accent bar: the one piece of colour, and it is the product's own accent.
    bar = max(10, int(w * 0.013))
    parts.append(f'<rect x="0" y="0" width="{bar}" height="{h}" fill="{ACCENT}"/>')

    # Mark + wordmark, top left, optically aligned on a shared baseline.
    top = int(h * 0.09)
    parts.append(MARK.format(x=m, y=top, s=f"{mark_s:.4f}", accent=ACCENT, ink50=INK_50))
    wm_cy = int(top + s["mark"] / 2.0)
    parts.append(
        f'<text x="{m + s["mark"] + int(s["mark"] * 0.34)}" y="{wm_cy}" '
        f'font-family="Inter, sans-serif" font-weight="600" font-size="{wm_sz}" '
        f'fill="{INK_50}" dominant-baseline="central">{WORDMARK}</text>'
    )

    # Headline block, vertically centred in the space between the header and the footer. Sizes are
    # the fitted ones, so the block height is real rather than nominal.
    header_bottom = top + s["mark"]
    foot_line_y = h - m - int(foot_sz * 2.4)
    block_h = h1_sz * 1.32 + sum(sz * 1.40 for sz in h2_sz)
    available = foot_line_y - header_bottom
    y = int(header_bottom + max((available - block_h) / 2.0, 0) + h1_sz * 0.92)
    parts.append(
        f'<text x="{m}" y="{y}" font-family="Inter, sans-serif" font-weight="600" '
        f'font-size="{h1_sz}" fill="{INK_50}">{H1}</text>'
    )
    y += int(h1_sz * 1.32)
    for line, sz in zip(H2, h2_sz):
        parts.append(
            f'<text x="{m}" y="{y}" font-family="Inter, sans-serif" font-weight="400" '
            f'font-size="{sz}" fill="{INK_300}">{line}</text>'
        )
        y += int(sz * 1.40)

    # Footer, pinned. Hairline above it so the claim reads as a disclosure, not a slogan.
    parts.append(
        f'<rect x="{m}" y="{foot_line_y}" width="{inner}" height="1" fill="{RULE}"/>'
    )
    parts.append(
        f'<text x="{m}" y="{h - m}" font-family="Inter, sans-serif" font-weight="400" '
        f'font-size="{foot_sz}" fill="{INK_400}">{FOOT}</text>'
    )
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def main():
    os.makedirs(OUT, exist_ok=True)
    written = []
    for name, s in SPECS.items():
        p = os.path.join(OUT, f"director-{name}.svg")
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(card(s))
        written.append({"file": os.path.relpath(p, ROOT), "w": s["w"], "h": s["h"]})
    print(json.dumps({"written": written}, indent=2))


if __name__ == "__main__":
    main()
