#!/usr/bin/env python3
"""build_summary.py — generate data/raw/<party>/SUMMARY.md (the M1 recon
deliverable) from sources.json + the archived local texts.

Usage: python3 agents/build_summary.py --party ndp
"""
import argparse, json, os, re
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TOPICS = {
    "cost-of-living-taxes": r"tax|affordab|cost of living|groceries|benefit|rebate|inflation|wage|speculat|vacanc|rent",
    "housing": r"hous|home|rent|condo|speculat|vacanc|homeless|zoning|rental",
    "health": r"health|doctor|nurse|hospital|surg|emergency|mental health|addiction|pharmacare|dental",
    "climate-environment": r"climate|emission|carbon|clean energy|renewab|LNG|forest|old growth|environment|conservation|protected area",
    "indigenous-reconciliation": r"Indigenous|First Nation|reconciliation|DRIPA|Declaration|UNDRIP|title|Métis|Inuit|residential school|Truth and Reconciliation",
    "public-safety": r"public safety|police|crime|bail|offender|gang|extortion|drug|toxic|victim|justice",
}
GROUP = {"platform": "Platform / plan documents", "policy": "Policy & issue pages",
         "release": "News releases", "speech": "Speeches", "hansard": "Legislature Hansard",
         "media": "Third-party media", "other": "Other (gov / party index)"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--party", required=True)
    a = ap.parse_args()
    outdir = os.path.join(ROOT, "data", "raw", a.party)
    recs = json.load(open(os.path.join(outdir, "sources.json")))

    bodies = {}
    for r in recs:
        tp = r.get("text_path") or ""
        bodies[r["id"]] = (open(os.path.join(ROOT, tp), encoding="utf-8", errors="replace").read()
                           if tp and os.path.exists(os.path.join(ROOT, tp)) else "")
    hits = {r["id"]: {t: len(re.findall(rx, bodies[r["id"]], re.I)) for t, rx in TOPICS.items()}
            for r in recs}

    n_arch = sum(1 for r in recs if r.get("archive_url"))
    n_text = sum(1 for r in recs if r.get("text_path"))
    by_type = Counter(r["type"] for r in recs)
    fresh = [r for r in recs if (r.get("published") or "") >= "2026-01-01"]
    legacy = [r for r in recs if (r.get("published") or "") < "2024-12-31" and r.get("published")]

    L = []
    L.append(f"# M1 Recon — source inventory: BC NDP")
    L += [
        "",
        "_Generated by `agents/build_summary.py` from `data/raw/ndp/sources.json`. "
        "Every source below is saved locally, sha256-hashed and — where the Wayback "
        "Machine accepted it — archived._",
        "",
        "## Headline numbers",
        "",
        f"- **{len(recs)} sources** inventoried, ids `ndp-0001` … `ndp-{len(recs):04d}` (contiguous, no gaps).",
        f"- **{n_arch}/{len(recs)} archived** to the Wayback Machine; {len(recs) - n_arch} could not be "
        "archived because `web.archive.org/save` returned **HTTP 429 (IP rate-limited)** after ~30 submissions. Retry later.",
        f"- **{n_text}/{len(recs)} have extracted plain text** (`*.txt`). One exception: `ndp-0004` (platform-highlights PDF) "
        "has no text layer — it is a graphics PDF; `pdftotext` returns nothing.",
        f"- **{len(fresh)} sources are from the 2026 campaign/legislature cycle** "
        "(published ≥ 2026-01-01). These are the ones that matter for coding.",
        f"- **{len(legacy)} sources are legacy (2017/2024)** and must not be coded as the current position "
        "without a 2026 confirmation. See *Freshness* below.",
        "",
        "## Inventory by type",
        "",
        "| type | n |",
        "|---|---|",
    ]
    for t, n in by_type.most_common():
        L.append(f"| {GROUP.get(t, t)} | {n} |")

    L += ["", "## The source list", "",
          "| id | type | published | arch | text | title |",
          "|---|---|---|---|---|---|"]
    for r in recs:
        L.append(f"| {r['id']} | {r['type']} | {r.get('published') or '—'} | "
                 f"{'yes' if r.get('archive_url') else '**no**'} | "
                 f"{'yes' if r.get('text_path') else '**no**'} | {(r.get('title') or '')[:72]} |")

    L += ["", "## Freshness — do not code a 2017/2024 page as today's position", "",
          "The party site mixes eras. The NDP's own site still serves 2017 (Horgan) and 2024 "
          "(last election) material next to 2026 campaign material:", ""]
    for r in legacy:
        L.append(f"- `{r['id']}` **{r['published']}** — {r.get('title')} — {r['url']}")
    L += ["",
          "Coding rule for M3: a code must cite a source dated **2026** unless the 2026 record "
          "explicitly re-affirms the older commitment. Legacy pages can support *background* only.",
          ""]

    L += ["## Where the evidence actually is, by topic", "",
          "Keyword hits in the archived text (rough signal, not a code). Full matrix: `data/raw/ndp/COVERAGE.md`.",
          "",
          "| topic | best 2026 sources (hits) |",
          "|---|---|"]
    for t in TOPICS:
        ranked = sorted([r for r in recs if (r.get("published") or "") >= "2026-01-01"],
                        key=lambda r: -hits[r["id"]][t])[:4]
        cell = ", ".join(f"`{r['id']}` ({hits[r['id']][t]})" for r in ranked if hits[r["id"]][t] > 0) or "**no 2026 hit — gap**"
        L.append(f"| {t} | {cell} |")

    L += ["", "## Recommended coding set (highest value, all 2026)", "",
          "If M3 coders want a compact, defensible evidence base rather than all 40:",
          "",
          "1. `ndp-0002` — campaign launch, Sept 22 2026: the framing of the whole platform (Trump-proof economy, lower costs, healthcare hiring).",
          "2. `ndp-0006` — “Built in B.C. and Canada” procurement rules, Sept 24 2026 (economy/jobs).",
          "3. `ndp-0007` — Unsold Condo Tax + speculation/vacancy tax increase, Sept 25 2026 (housing; the sharpest, most specific housing commitment of the campaign).",
          "4. `ndp-0009` — critical minerals + Port of Prince Rupert expansion, Sept 28 2026 (economy/environment trade-off).",
          "5. `ndp-0008` — LNG position, Sept 28 2026 (climate: the NDP's own framing of the LNG file).",
          "6. `ndp-0017` — largest private-sector investment claim, Sept 29 2026 (economy).",
          "7. `ndp-0018` — Truth and Reconciliation statement, Sept 30 2026 (Indigenous reconciliation; note it is a values statement, not a policy commitment).",
          "8. `ndp-0025` / `ndp-0026` / `ndp-0028` — 2026 Hansard (Feb 19, Mar 30, May 27). Richest health, housing, climate and reconciliation passages, in the government's own words.",
          "9. `ndp-0014`/`ndp-0016` — the party's own framing of its opponents' health promises (useful for seeing where the NDP has *chosen* to draw lines).",
          "10. `ndp-0035` — BC Ballot's cross-party platform comparison (last checked Oct 1 2026) — useful to confirm the NDP has **no single published 2026 platform document**.",
          "",
          "## Gaps and risks for M3",
          "",
          "- **No 2026 platform document.** As of Oct 1 2026 the NDP has no single platform PDF/plan page; "
          "positions have to be assembled from the daily releases plus the record in the legislature. "
          "BC Ballot's tracker agrees. Anything coded as a party position must therefore name a specific release or Hansard passage.",
          "- **Indigenous reconciliation is thin and contested.** `ndp-0012` is from 2017; `ndp-0018` is a "
          "statement of values; `ndp-0037` is a news story about the government pausing DRIPA amendments. "
          "There is no 2026 NDP document stating its DRIPA position. Expect a low-confidence code here, "
          "or flag it for the human gate.",
          "- **Climate vs. economy tension.** `ndp-0008` (LNG) and `ndp-0009` (critical minerals) are the "
          "government's own defence of resource expansion. Coders must decide whether to read that as "
          "pro-development on the climate statement; do not let one coder treat them differently from another.",
          "- **Health is only in Hansard and third-party framing.** There is no 2026 NDP health-budget "
          "release in this set. `ndp-0025` (Feb 19) has the fullest government-side argument.",
          "- **Archive coverage is 29/40.** Several of the recommended coding sources are in the "
          "unarchived 11. Re-run `python3 agents/archive_retry.py --party ndp` in a few hours when the "
          "Wayback rate limit clears; do not treat “no archive_url” as “not fetched”.",
          "",
          "## Repo / coordination note",
          "",
          "While this inventory was being built, at least one other worker was writing "
          "`data/raw/ndp/` at the same time (duplicate ids, duplicated urls, a stray "
          "`ndp-platformhighlights.pdf`). `agents/consolidate_sources.py` dedupes by url and by "
          "file content and renumbers contiguously; `agents/repair_sources.py` re-fetches any record "
          "whose file went missing. **Only one worker should write a given party directory at a time.**",
          "",
          "## Reproduce",
          "",
          "```bash",
          "# fetch one source",
          "python3 agents/fetch_source.py --party ndp --url <url> --type release --title '...' --published 2026-09-25",
          "# clean up if more than one worker touched this directory",
          "python3 agents/consolidate_sources.py --party ndp",
          "python3 agents/repair_sources.py --party ndp",
          "python3 agents/archive_retry.py --party ndp",
          "python3 agents/extract_published.py --party ndp",
          "python3 agents/topical_coverage.py --party ndp",
          "python3 agents/build_summary.py --party ndp",
          "```",
          ""]

    out = "\n".join(L) + "\n"
    open(os.path.join(outdir, "SUMMARY.md"), "w", encoding="utf-8").write(out)
    print(out)


if __name__ == "__main__":
    main()
