#!/usr/bin/env python3
"""build_summary_party.py — generate data/raw/<party>/SUMMARY.md (the M1 recon
deliverable) from sources.json + the archived local texts, for any party.

Usage: python3 agents/build_summary_party.py --party cpb
"""
import argparse, json, os, re
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TOPICS = {
    "cost-of-living-taxes": r"tax|affordab|cost of living|groceries|benefit|rebate|inflation|wage|speculat|vacanc|rent",
    "housing": r"hous|home|rent|condo|speculat|vacanc|homeless|zoning|rental",
    "health": r"health|doctor|nurse|hospital|surg|emergency|mental health|addiction|pharmacare|dental",
    "climate-environment": r"climate|emission|carbon|clean energy|renewab|LNG|forest|old growth|environment|conservation|protected area",
    "indigenous-reconciliation": r"Indigenous|First Nation|reconciliation|DRIPA|Declaration|UNDRIP|title|Métis|Inuit|residential school|Truth and Reconciliation",
    "public-safety": r"public safety|police|crime|bail|offender|gang|extortion|drug|toxic|victim|justice",
}
GROUP = {"platform": "Platform / plan documents", "policy": "Policy & issue pages",
         "release": "News releases", "speech": "Speeches", "hansard": "Legislature Hansard",
         "media": "Third-party media", "other": "Other (party index / background)"}
TITLE = {"cpb": "BC Conservatives", "ndp": "BC NDP", "green": "BC Greens",
         "onebc": "OneBC", "centrebc": "CentreBC"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--party", required=True)
    a = ap.parse_args()
    outdir = os.path.join(ROOT, "data", "raw", a.party)
    recs = json.load(open(os.path.join(outdir, "sources.json")))
    name = TITLE.get(a.party, a.party)

    bodies = {}
    for r in recs:
        tp = r.get("text_path") or ""
        bodies[r["id"]] = (open(os.path.join(ROOT, tp), encoding="utf-8", errors="replace").read()
                           if tp and os.path.exists(os.path.join(ROOT, tp)) else "")
    hits = {r["id"]: {t: len(re.findall(rx, bodies[r["id"]], re.I)) for t, rx in TOPICS.items()}
            for r in recs}

    n_arch = sum(1 for r in recs if r.get("archive_url"))
    n_text = sum(1 for r in recs if r.get("text_path"))
    by_type = Counter(r["type"] for r in recs)
    fresh = [r for r in recs if (r.get("published") or "") >= "2026-01-01"]
    legacy = [r for r in recs if r.get("published") and r["published"] < "2026-01-01"]
    notext = [r for r in recs if not r.get("text_path")]

    L = []
    L.append(f"# M1 Recon — source inventory: {name}")
    L += ["", "_Generated by `agents/build_summary_party.py` from "
          f"`data/raw/{a.party}/sources.json`. Every source below is saved locally, "
          "sha256-hashed and — where the Wayback Machine accepted it — archived._", "",
          "## Headline numbers", "",
          f"- **{len(recs)} sources** inventoried, ids `{a.party}-0001` … `{a.party}-{len(recs):04d}` (contiguous, no gaps).",
          f"- **{n_arch}/{len(recs)} archived** to the Wayback Machine. The rest could not be archived "
          "(`web.archive.org/save` rate-limits by IP); retry with `agents/archive_retry.py`. "
          "\"no archive_url\" never means \"not fetched\" — the bytes are on disk and hashed.",
          f"- **{n_text}/{len(recs)} have extracted plain text** (`*.txt`). Without text: "
          + (", ".join(f"`{r['id']}` ({r.get('title','')[:40]})" for r in notext) or "none") + ".",
          f"- **{len(fresh)} sources are 2026** (published ≥ 2026-01-01) — the campaign/legislature cycle that matters for coding.",
          f"- **{len(legacy)} sources are pre-2026** background and must not be coded as the current position.",
          "", "## Inventory by type", "", "| type | n |", "|---|---|"]
    for t, n in by_type.most_common():
        L.append(f"| {GROUP.get(t, t)} | {n} |")

    L += ["", "## The source list", "",
          "| id | type | published | arch | text | title |", "|---|---|---|---|---|---|"]
    for r in recs:
        L.append(f"| {r['id']} | {r['type']} | {r.get('published') or '—'} | "
                 f"{'yes' if r.get('archive_url') else '**no**'} | "
                 f"{'yes' if r.get('text_path') else '**no**'} | {(r.get('title') or '')[:72]} |")

    L += ["", "## Freshness — pre-2026 pages are background, not the current position", "",
          f"As of 2026-10-01 the party has **no published 2026 platform document** — the "
          "Our Platform page is a set of topic cards only (\"coming soon\"). Pre-2026 material in this set:", ""]
    for r in legacy:
        L.append(f"- `{r['id']}` **{r['published']}** — {r.get('title')} — {r['url']}")
    L += ["", "Coding rule for M3: a code must cite a source dated **2026** unless the 2026 record "
          "explicitly re-affirms the older commitment. Legacy documents support *background* only.", "",
          "## Where the evidence actually is, by topic", "",
          f"Keyword hits in the archived text (rough signal, not a code). Full matrix: "
          f"`data/raw/{a.party}/COVERAGE.md`.", "", "| topic | best 2026 sources (hits) |", "|---|---|"]
    for t in TOPICS:
        ranked = sorted(fresh, key=lambda r: -hits[r["id"]][t])[:4]
        cell = ", ".join(f"`{r['id']}` ({hits[r['id']][t]})" for r in ranked if hits[r["id"]][t] > 0) \
            or "**no 2026 hit — gap**"
        L.append(f"| {t} | {cell} |")

    L += ["", "## Gaps and risks for M3", "",
          "- **No 2026 platform document.** Everything coded as a 2026 party position must cite a "
          "specific release, the Policy Declaration, or a Hansard passage — not a platform PDF that does not exist.",
          "- **`%s-0005` (BC Energy Superpower PDF) has no usable text layer** — it is a design PDF with "
          "per-glyph positioning, so `pdftotext` output is unquotable. Read the PDF visually, or quote the "
          "HTML release `%s-0011` and the news coverage (`%s-0034/0035/0037/0038`) for the same commitments." % (a.party, a.party, a.party),
          "- **Leader churn.** Kerry-Lynne Findlay resigned and Lorne Doerkson became **interim** leader in "
          "Sept 2026 (`%s-0027`, `%s-0028`), days before the snap election. Doerkson's statements are the "
          "party's current position; a permanent leader has not been installed." % (a.party, a.party),
          "- **Archive coverage is partial.** Re-run `python3 agents/archive_retry.py --party %s` later; "
          "the local hashed copy is the provenance of record regardless." % a.party,
          "", "## Repo / coordination note", "",
          "More than one worker wrote `data/raw/%s/` concurrently (duplicate ids, duplicated urls, "
          "stray `cpb-00NN.pdf` orphans). `agents/consolidate_sources.py` dedupes by normalised url and by "
          "file content hash, renumbers ids contiguously and deletes orphans; `agents/repair_sources.py` "
          "re-fetches any record whose file went missing. **Only one worker should write a given party "
          "directory at a time.**" % a.party, "", "## Reproduce", "", "```bash",
          f"# bulk fetch from the manifest",
          f"python3 agents/fetch_manifest.py data/manifests/{a.party}.json",
          f"# one-off source (HTML) / PDF",
          f"python3 agents/fetch_source.py --party {a.party} --url <url> --type release --title '...' --published 2026-09-25",
          f"python3 agents/fetch_pdf.py --party {a.party} --url <url.pdf> --type policy --title '...'",
          f"# clean up if more than one worker touched this directory",
          f"python3 agents/consolidate_sources.py --party {a.party}",
          f"python3 agents/repair_sources.py --party {a.party}",
          f"python3 agents/archive_retry.py --party {a.party}",
          f"python3 agents/extract_published.py --party {a.party}",
          f"python3 agents/topical_coverage.py --party {a.party}",
          f"python3 agents/build_summary_party.py --party {a.party}",
          "```", ""]

    out = "\n".join(L) + "\n"
    open(os.path.join(outdir, "SUMMARY.md"), "w", encoding="utf-8").write(out)
    print(out)


if __name__ == "__main__":
    main()
