#!/usr/bin/env python3
"""make_codings_doc.py — human-readable M3 coding table from data/codings/*.json."""
import json, os
from collections import defaultdict

ROOT = '.'
REPO = f'{ROOT}/data/codings'
PARTIES = ['ndp', 'cpb', 'green', 'onebc', 'centrebc']
NAMES = {'ndp': 'BC NDP', 'cpb': 'BC Conservatives', 'green': 'BC Greens',
         'onebc': 'OneBC', 'centrebc': 'CentreBC'}
QIDS = ['q01','q03','q04','q10','q11','q18','q19','q22','q26','q28','q29','q31',
        'q37','q38','q39','q46','q47','q48']


def snippet(q, n=110):
    if not q:
        return ''
    q = ' '.join(q.split())
    return q if len(q) <= n else q[:n - 1] + '…'


def main():
    qs = {q['id']: q for q in json.load(open(f'{ROOT}/data/questions/questions.json'))}
    fp = {q['id']: q for q in json.load(open(f'{ROOT}/data/questions/freeze-proposal.json'))}
    ver = json.load(open(f'{REPO}/_verification.json'))
    conf = json.load(open(f'{REPO}/_conflicts.json'))
    quar = json.load(open(f'{REPO}/_quarantined.json'))
    aud = json.load(open(f'{REPO}/_citation_audit.json'))

    rows = {}
    for p in PARTIES:
        f = f'{REPO}/{p}.json'
        rows[p] = json.load(open(f)) if os.path.exists(f) else []
    byc = {p: defaultdict(dict) for p in PARTIES}
    for p in PARTIES:
        for r in rows[p]:
            byc[p][r['coder']][r['question_id']] = r

    L = []
    L.append('# BC Vote Match — M3 Coding Table')
    L.append('')
    L.append('_Generated by `agents/verify_and_aggregate.py` + `agents/make_codings_doc.py` · '
             'version `v0.9-prefreeze` · **provisional**_')
    L.append('')
    L.append('> **Status: PROVISIONAL.** The M2 freeze gate (`<task-id>`) is still awaiting human '
             'sign-off, so this table is coded against the **proposed** 18-statement set '
             '(`data/questions/freeze-proposal.json`), not yet against `data/questions/questions.json`. '
             'If the gate swaps any statement, only the swapped rows need re-coding.')
    L.append('')
    L.append('## Method')
    L.append('')
    L.append('Two independent coders per party (never shown each other’s work), each producing one '
             'code per statement on the contract scale (see `docs/SCHEMA.md`): '
             '`-2` strongly disagree · `-1` disagree · `0` explicitly neutral · `+1` agree · '
             '`+2` strongly agree · `null` = the party has no stated position (never guessed).')
    L.append('')
    L.append('Every non-null row ships a **verbatim quote**. Each quote is checked mechanically '
             'as an exact substring of the stored source file; the cited source must also be a '
             'trusted record (stored bytes hash-matching its `sources.json` entry). A quote that '
             'does not verify is never edited: if the same verbatim text exists in another trusted '
             'source of the same party, the citation is re-pointed to that record (logged in '
             '`data/codings/_citation_audit.json`); otherwise the row is quarantined '
             '(`_quarantined.json`) and excluded here.')
    L.append('')
    L.append(f'- citation re-points: **{len(aud)}**')
    L.append(f'- quarantined rows: **{len(quar)}**')
    L.append(f'- source snapshot (sources.json sha256): ' +
             ', '.join(f'`{p}`={ver["source_snapshot_sha256"][p][:12]}' for p in PARTIES))
    L.append('')
    L.append('## Coverage and agreement')
    L.append('')
    L.append('| party | coder rows | coded (non-null) | both coded same | coder split | both null |')
    L.append('|---|---|---|---|---|---|')
    for p in PARTIES:
        d = ver['parties'][p]
        nonnull = sum(1 for r in rows[p] if r['code'] is not None)
        L.append(f"| {NAMES[p]} | {d['rows_written']} | {nonnull} | {d['agree']} | "
                 f"{d['disagree']} | {d['both_null']} |")
    L.append('')
    L.append('## The coding table')
    L.append('')
    L.append('`A` / `B` are the two independent coders. `split` marks a row where the coders '
             'disagreed — those go to the adversarial verification pass and, if still unresolved, '
             'to a human tie-break.')
    L.append('')
    for p in PARTIES:
        L.append(f'### {NAMES[p]} (`{p}`)')
        L.append('')
        L.append('| id | statement | A | B | split | source (A) | quote |')
        L.append('|---|---|---|---|---|---|---|')
        for q in QIDS:
            a = byc[p].get(f'{p}-coder-a', {}).get(q)
            b = byc[p].get(f'{p}-coder-b', {}).get(q)
            ca = a['code'] if a else '—'
            cb = b['code'] if b else '—'
            split = '⚠' if (a and b and ca != cb) else ''
            src = a.get('source_id') if a and a.get('code') is not None else ''
            qq = snippet(a.get('quote')) if a else ''
            st = qs.get(q, {}).get('statement', fp.get(q, {}).get('statement', ''))
            L.append(f"| {q} | {st} | {ca} | {cb} | {split} | {src} | {qq} |")
        L.append('')
    L.append('## Coder splits (for adversarial verification)')
    L.append('')
    if not conf:
        L.append('None recorded.')
    else:
        for c in conf:
            L.append(f"- **{NAMES[c['party_slug']]} / {c['question_id']}**: "
                     f"A={c['coder_a']['code']} B={c['coder_b']['code']}")
            L.append(f"  - A quote: “{snippet(c['coder_a']['quote'], 160)}”")
            L.append(f"  - B quote: “{snippet(c['coder_b']['quote'], 160)}”")
    L.append('')
    L.append('## Next steps')
    L.append('')
    L.append('1. `<task-id>` (adversarial verification) re-codes each party blind and '
             'escalates the splits above.')
    L.append('2. `<task-id>` (M2 human gate) approves or swaps the 18; the freeze is applied to '
             '`data/questions/questions.json` and this table is re-stamped `v1`.')
    L.append('3. M5 integration reads `data/codings/<party>.json` unchanged.')
    out = '\n'.join(L) + '\n'
    open(f'{ROOT}/docs/04-CODINGS.md', 'w', encoding='utf-8').write(out)
    print('wrote docs/04-CODINGS.md', len(out), 'chars')


if __name__ == '__main__':
    main()
